services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    networks:
      - monitor-net
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      volumes:
        - /home/krayu/calc/Simple-Flask-Calculator/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - monitor-net
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - monitor-net
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  monitor-net:
    driver: bridge
